from fpdf import FPDF

def create_table(pdf, title, subtitle, days_count, periods_config, schedule_grid):
    pdf.add_page(orientation="L") 
    
    # Header Background
    pdf.set_fill_color(245, 247, 250)
    pdf.rect(0, 0, pdf.w, 40, "F")
    
    # Institution Name
    pdf.set_font("Times", "B", 22)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(0, 15, title, align="C", new_x="LMARGIN", new_y="NEXT")
    
    # Subtitle
    if subtitle:
        pdf.set_font("Times", "I", 12)
        pdf.set_text_color(71, 85, 105)
        pdf.cell(0, 8, subtitle, align="C", new_x="LMARGIN", new_y="NEXT")
    
    pdf.ln(10)
    
    # Table Config
    total_cols = days_count + 1
    col_width = (pdf.w - 30) / total_cols
    pdf.set_left_margin(15)
    
    # Table Header
    pdf.set_fill_color(51, 65, 85)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Times", "B", 11)
    
    pdf.cell(col_width, 10, "Time", border=1, align="C", fill=True)
    day_names = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
    for d in range(days_count):
        pdf.cell(col_width, 10, day_names[d], border=1, align="C", fill=True)
    pdf.ln()
    
    # Table Content
    pdf.set_text_color(30, 41, 59)
    pdf.set_font("Times", "", 10)
    row_height = 16 if len(periods_config) <= 7 else 14
    
    for p, p_conf in enumerate(periods_config):
        # Time column
        pdf.set_fill_color(248, 250, 252)
        time_text = f"{p_conf.label}\n{p_conf.start_time}-{p_conf.end_time}"
        pdf.multi_cell(col_width, row_height/2, time_text, border=1, align="C", fill=True, new_x="RIGHT", new_y="TOP", max_line_height=row_height/2)
        
        # Days
        for d in range(days_count):
            if p_conf.is_break:
                pdf.set_fill_color(241, 245, 249)
                pdf.set_font("Times", "I", 9)
                pdf.multi_cell(col_width, row_height, "BREAK", border=1, align="C", fill=True, new_x="RIGHT", new_y="TOP", max_line_height=row_height)
                pdf.set_font("Times", "", 10)
            else:
                content = schedule_grid[d][p]
                pdf.multi_cell(col_width, row_height/2, content if content else "", border=1, align="C", new_x="RIGHT", new_y="TOP", max_line_height=row_height/2)
            
        pdf.ln(row_height)
    
    # Footer
    pdf.set_y(-20)
    pdf.set_font("Times", "I", 8)
    pdf.set_text_color(148, 163, 184)
    pdf.cell(0, 10, "Generated by TimetablePro - Stateless Zero-Config Scheduling", align="R")

def generate_class_pdf(institution_name, config, classes, staff_list, class_schedule):
    pdf = FPDF(orientation="Landscape")
    days_count = 6 if config.include_saturday else 5
    for cls_obj in classes:
        c = cls_obj.name
        # Find class teacher
        class_teacher = "Not Assigned"
        for s in staff_list:
            if s.class_teacher_for == c:
                class_teacher = s.name
                break
        
        grid = [["" for _ in range(len(config.periods))] for _ in range(days_count)]
        for d in range(days_count):
            for p in range(len(config.periods)):
                slot = class_schedule[c][d][p]
                if slot:
                    grid[d][p] = f"{slot['subject']}\n{slot['teacher']}"
        
        create_table(pdf, institution_name, f"Class: {c}  |  Class Teacher: {class_teacher}", days_count, config.periods, grid)
    return pdf.output()

def generate_staff_pdf(institution_name, config, staff_names, class_schedule):
    pdf = FPDF(orientation="Landscape")
    days_count = 6 if config.include_saturday else 5
    staff_schedule = {s: [["" for _ in range(len(config.periods))] for _ in range(days_count)] for s in staff_names}
    for c, days_list in class_schedule.items():
        for d in range(days_count):
            for p in range(len(config.periods)):
                slot = days_list[d][p]
                if slot:
                    teacher = slot["teacher"]
                    if teacher in staff_schedule:
                        if not staff_schedule[teacher][d][p]:
                            staff_schedule[teacher][d][p] = f"Class {c}\n{slot['subject']}"
                        
    for s in staff_names:
        create_table(pdf, institution_name, f"Staff Schedule: {s}", days_count, config.periods, staff_schedule[s])
    return pdf.output()
